### ISSUE TITLE
/Osmedeus/lib/alias/dirscan iisue

### ISSUE THREAD

**Issue by 0x240x23elu** [j3ssie/osmedeus#100]
Hi i have issue 
----------------------------------------------------------------------
Something went wrong with the command below: 
/root/Downloads/alltest/Osmedeus/lib/alias/dirscan -i https://info.lifeomic.com/FUZZ -w '/root/Downloads/alltest/Osmedeus/data/wordlists/content/top10000.txt' -o '/root/.osmedeus/workspaces/lifeomic.com/directory/raw' -p '/root/Downloads/alltest/Osmedeus/plugins/go' -s '/root/.osmedeus/workspaces/lifeomic.com/directory'

so why you not run direct 

dirscan -i https://info.lifeomic.com/FUZZ -w '/root/Downloads/alltest/Osmedeus/data/wordlists/content/top10000.txt' -o '/root/.osmedeus/workspaces/lifeomic.com/directory/raw' -p '/root/Downloads/alltest/Osmedeus/plugins/go' -s '/root/.osmedeus/workspaces/lifeomic.com/directory'

dirscan in already install in kali and other go also so you can run directly .

**Comment by 0x240x23elu** [comment]
i think https://info.lifeomic.com/FUZZ is come with wfuzz

**Comment by j3ssie** [comment]
### For the error
Can you check if `/root/Downloads/alltest/Osmedeus/data/wordlists/content/top10000.txt` exist in your machine?

### Detail about that file
It's actually an alias to run **ffuf** which is you can see from here https://github.com/j3ssie/Osmedeus/blob/master/lib/alias/dirscan#L22

The reason why I don't run it's directly because it's required some check after that command has done.
I can create a function on `modules/dirbscan.py` for it but since this need to run each URL for it, doing that gonna cause some mess.

**Comment by 0x240x23elu** [comment]
i had check it is exist

**Comment by j3ssie** [comment]
Can you this command directly 
```/root/Downloads/alltest/Osmedeus/lib/alias/dirscan -i https://info.lifeomic.com/FUZZ -w '/root/Downloads/alltest/Osmedeus/data/wordlists/content/top10000.txt' -o '/root/.osmedeus/workspaces/lifeomic.com/directory/raw' -p '/root/Downloads/alltest/Osmedeus/plugins/go' -s '/root/.osmedeus/workspaces/lifeomic.com/directory'```

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
