### ISSUE TITLE
is killing my internet

### ISSUE THREAD

**Issue by soupnatzi** [j3ssie/osmedeus#109]
Great tool I love it but When I run the tool it kills my internet anyway around this issue guys?

**Comment by getsec** [comment]
@soupnatzi  Can you provide a little more detail. I'm sure the tool generates a lot of outbound traffic, but killing your internet seems a little odd. Do you lose all connections from your local machine? Is your outbound traffic slow while running the tool, a little more detail would go a long way.

**Comment by soupnatzi** [comment]
hi @getsec yes when i run it everything else stops kills my internet on everything else as far streaming connecting to the internet everything it just kills it.

**Comment by j3ssie** [comment]
Yeah, if you have slow Internet you may get this issue because **Osmedeus** sending a lot of traffic especially some modules with **massdns**, **masscan** or even **httprobe** if you found a lot of subdomain.

Can you only run subdomain module to see any different `./osmedeus.py -m sub -t example.com` because that's a module not sending much traffic outside.

**Comment by soupnatzi** [comment]
I have a very fast internet so that's not the issue but I will try what you suggested and post results.

**Comment by fuomag9** [comment]
@soupnatzi it could also be your router, I had to switch from the provider mandatory router (vodafone) to a "professional" one (I'm using the edgerouter 3 lite ) and my issues were fixed

**Comment by s41n1k** [comment]
In my case,
While osmedeus scan about port module then my internet get loss.

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
