### ISSUE TITLE
suggestions about proxy 

### ISSUE THREAD

**Issue by v5pingan** [j3ssie/Osmedeus#41]
Some suggestions:

Can you add the function of agent pool?

Functions similar to this project:
Https://github.com/odboy/shadowProxy

Thank you!

**Comment by j3ssie** [comment]
Yeah I already think about it but it's really hard to implement because Osmedeus run many different tools for each module and some of them not support proxy natively.

So the some ways to do it through a proxy is to config your OS through a proxy, use `proxychains-ng`, or use the tool above and config proxychains to it.

Let me know if you have any idea.

**Comment by v5pingan** [comment]
Currently, proxychains are used,
Contact you if you have new ideas.
Thank you!
