### ISSUE TITLE
problem running the framework

### ISSUE THREAD

**Issue by nxtsuki** [j3ssie/Osmedeus#57]
![Screenshot_17](https://user-images.githubusercontent.com/53132104/61615241-cc410b80-ac65-11e9-90ac-fa53825d0578.png)

Hello, i was trying to run the framework but it gives me those errors, i installed everything doing ./install.sh.

**Comment by j3ssie** [comment]
It seems Flask API can't access cert file on your system.
Could you verify that **cert.pem** and **key.pem** are exist in `Osmedeus/core/certs` folder.

If they exist just run `python3 core/app.py` to verify that you can run Flask API server properly.

**Comment by nxtsuki** [comment]
i have the .pem files, i tried running the command but it gives me the same errors

**Comment by j3ssie** [comment]
Flask server still can't access your cert file for some reason(maybe because Osmedeus required python **3.6+**).
But it looks like you're running on Debian which is not native support OS.
So could you verify that this is lines of code in `Osmedeus/core/app.py` is works?

```
# BASE_DIR = Path(os.path.dirname(os.path.abspath(__file__)))

# get core directory 
BASE_DIR = Path('/your/absolutelypath/Osmedeus')

cert_path = BASE_DIR.joinpath('certs/cert.pem')
key_path = BASE_DIR.joinpath('certs/key.pem')

print(str(cert_path))
print(str(key_path))

```
See if you can get the right path of your `*.pem` file.

**Comment by j3ssie** [comment]
Due to Osmedeus upgraded into v2.0, this issue is no longer exist.
Please use the new version and send me a feedback.
Thank you.
