### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by huashu2019** [j3ssie/Osmedeus#69]
[+] Installing amass 
./install.sh: line 107: get: command not found
[+] Installing subfinder 
./install.sh: line 109: get: command not found
[+] Installing gobuster 
./install.sh: line 111: get: command not found
[+] Installing aquatone 
./install.sh: line 113: get: command not found
[+] Installing gitrob 
./install.sh: line 115: get: command not found
[+] Installing subjack 
./install.sh: line 117: get: command not found
[+] Installing tko-subs 

--------------------------------------------------
What environments do you need to rely on?

Example:

Python 3.6

PIP3

PIP3 install flask flask_restful flask_jwt flask_cors flask_jwt_extended ansi2html

Yum-y group install "Development tools"

Yum-y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel

Yum install-y Git

Yum-y install curl

Do you need any other software support?

**Comment by huashu2019** [comment]
Can you provide paid installation service?

Or specify the dependent environments such as CentOS 7, Python 3.X, pip3, etc......

Mail: 100462728@qq.com

**Comment by j3ssie** [comment]
Your error appears because your OS doesn't have **go** installed and all others tools seem can't be also because **yum** command.

Maybe you should change OS to Kali Linux or use another OS support **apt** package manager like Ubuntu.

Read this for more [detail](https://j3ssie.github.io/Osmedeus/installation/).
