### ISSUE TITLE
Waiting for PortScan Module

### ISSUE THREAD

**Issue by dzhenway** [j3ssie/Osmedeus#96]
Hi Sir,

I love you tool, but i had problem when Starting Masscan

```
[+] Starting Masscan 65535 ports
[*] Execute: /home/wayc0de/tools/Osmedeus/lib/alias/portscan -i /home/wayc0de/.osmedeus/workspaces/target.com/probing/ip-target.com.txt -o '/home/wayc0de/.osmedeus/workspaces/target.com/portscan/target.com' -s '/home/wayc0de/.osmedeus/workspaces/target.com/portscan/summary.txt' -p '/home/wayc0de/tools/Osmedeus/plugins'
[sudo] password for wayc0de: [*] Waiting for PortScan module
[*] Waiting for PortScan module
[*] Waiting for PortScan module
[*] Waiting for PortScan module
[*] Waiting for PortScan module
```

How long i must wait for that? because more than 1 hours still waiting

Thank you

**Comment by j3ssie** [comment]
It's obviously **masscan** need root permissions so you have to provide your password if you're running as a non-root user. It's waiting too long because you don't provide that so it's never actually run :).

I normally run Osmedeus as a root user or you can whitelist some command need to run as root like **masscan** and **nmap**. [Reference](https://unix.stackexchange.com/questions/18830/how-to-run-a-specific-program-as-root-without-a-password-prompt)

**Comment by dzhenway** [comment]
hi @j3ssie 

thank you, ill try it

**Comment by dzhenway** [comment]
hi @j3ssie 

successfully running as a non-root user

## Step by Step

1. Edit `sudoers` use `sudo nano /etc/sudoers`, and then add this parameter

```
# Allow members of group sudo to execute any command
%sudo ALL=(ALL:ALL) ALL
myusername ALL = (ALL) ALL
myusername ALL = (root) NOPASSWD: ALL
```

2. Try run Osmedeus as a non-root and Masscan running smoothly

**Comment by j3ssie** [comment]
Very nice, I will note that in the document when I have free time :).
