### ISSUE TITLE
Portscan very slow 

### ISSUE THREAD

**Issue by 0x240x23elu** [j3ssie/osmedeus#97]
Hi,

 when portscan run it run very slow , 35 target its take time whole night ,

can we run as nmap -sC -sV  -pP -A target so we can do fast scan

**Comment by j3ssie** [comment]
Portscan module using masscan and Vulnscan module using nmap.
It depends on the network of machine running **Osmedeus**. And of course nmap really slow that's why I'm not included it in the main routine.

Did you test your nmap command with mine?
I thought your nmap command is even slower than mine except you do not specify 65k ports.

**Comment by 0x240x23elu** [comment]
i know but what about nmap -sC -sV -A target  it will not take time more then amass

**Comment by j3ssie** [comment]
What do you mean by that? You mean we can start the **nmap** right after we got the IP range from **Amass** or **IPSpace** modules?

If your point is that **Osmedeus** can absolutely do it but nmap or portscan gonna eat all your network bandwidth then cause so many false positive on other modules. That's why I leave it at the end of the routine.

**Comment by dwisiswant0** [comment]
@j3ssie i recommended it, https://github.com/projectdiscovery/naabu

**Comment by j3ssie** [comment]
The issue is no longer exist due to the repo having been upgraded to [Osmedeus Next Generation v4.0](https://twitter.com/OsmedeusEngine)
